# Generated by Django 5.2.4 on 2025-07-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='librarian',
            options={},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={},
        ),
    ]
